### ISSUE TITLE
Multi datastore integration failures, wrong connection for explain

### ISSUE THREAD

**Issue by DerekStride** [GraphQL-Query-Planner/graphql-analyzer#6]
When integrating the analyzer with a active record project that has a specific table with a different datastore connection from the default ActiveRecord::Base, trying to execute the explain query sends the request to the wrong datastore connection.

```
Failures:

  1) tables backed by specific datastore connections parses each query only once
     Failure/Error: result["extensions"] ||= {}

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./lib/graphql/analyzer.rb:34:in `after_query'
     # ./spec/graphql/analyzer/instrumentation/active_record_spec.rb:98:in `block (2 levels) in <top (required)>'
     # ./spec/graphql/analyzer/instrumentation/active_record_spec.rb:104:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Mysql2::Error:
     #   You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.* FROM "pg_users" WHERE "pg_users"."id" = $1 LIMIT $2' at line 1
     #   ./lib/graphql/analyzer/instrumentation/base.rb:15:in `block in instrument'

Finished in 59 minutes 28 seconds (files took 1.02 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/graphql/analyzer/instrumentation/active_record_spec.rb:103 # tables backed by specific datastore connections parses each query only once
```

**Comment by DerekStride** [comment]
NOT Finished, this error is uncommon and fights against ActiveRecord, so a custom instrument could be created to deal with this case.
